services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


parameters:
    app.jwt_ttl: '%env(int:JWT_TOKEN_TTL)%'
    app.jwt_refresh_ttl: '%env(int:JWT_REFRESH_TOKEN_TTL)%'
    app.rate_limit_login_attempts: '%env(int:RATE_LIMITER_LOGIN_ATTEMPTS)%'
    app.rate_limit_login_interval: '%env(string:RATE_LIMITER_LOGIN_INTERVAL)%'
