api_platform:
    title: 'Sooatek Authentication API'
    version: '1.0.0'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
    formats:
        json:
            mime_types: ['application/json']
    patch_formats:
        json:
            mime_types: ['application/merge-patch+json']
    swagger:
        versions: [3]
    openapi:
        contact:
            name: 'Sooatek Support'
            email: 'support@sooatek.test'
