framework:
    rate_limiter:
        login:
            policy: 'fixed_window'
            limit: '%env(int:RATE_LIMIT_LOGIN_ATTEMPTS)%'
            interval: '%env(string:RATE_LIMIT_LOGIN_INTERVAL)%'
            cache_pool: cache.rate_limiter
